export default [
  {
    id: '1',
    plate: 'INX-5175',
    make: 'Ferrari',
    model: '812 Super Fast',
    year: 2021,
    mileage: 0,
    addons: ['ABS', 'AC'],
  },
  {
    id: '2',
    plate: 'INX-5175',
    make: 'BMW',
    model: 'Z4',
    year: 2016,
    mileage: 95000,
    addons: ['ABS', 'electric_wheel'],
  },
  {
    id: '3',
    plate: 'ILO-6912',
    make: 'Bentley',
    model: ' Continental GT',
    year: 2019,
    mileage: 52000,
    addons: ['ABS', 'AC', 'airbag'],
  },
  {
    id: '4',
    plate: 'INX-5175',
    make: 'Range Rover ',
    model: 'LVB',
    year: 2020,
    mileage: 20700,
    addons: ['ABS', '4x4'],
  },
  {
    id: '5',
    plate: 'SKS-4612',
    make: 'Jaguar',
    model: 'FTYPE',
    year: 2020,
    mileage: 22000,
    addons: ['electric_wheel'],
  },
  {
    id: '6',
    plate: 'JKL-2131',
    make: 'Lamborghini ',
    model: 'Huracan EVO Spyder',
    year: 2017,
    mileage: 76000,
    addons: ['ABS', 'AC'],
  },
  {
    id: '7',
    plate: 'IJK-2222',
    make: 'Audi ',
    model: 'R8',
    year: 2012,
    mileage: 120030,
    addons: [],
  },
];
